# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeProject-TBD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeProject-TBD
  pod 'PhoneNumberKit', '~> 3.3'
  pod 'MessageKit'
  pod 'MessageInputBar'
  pod 'InputBarAccessoryView'

end
